### ISSUE TITLE
change style name for MapboxMap

### ISSUE THREAD

**Issue by kodermax** [MeilleursAgents/react-mapbox-wrapper#16]
Please change name of field style for MapboxMap.
for example: mapStyle.
I can make PR.

**Comment by Heisendev** [comment]
Hi! 
just to exactly know what the problem is, can you explain why do you want/need this change ? 

You're welcome to open a PR 😄  ( don't forget to follow the [pull_request_template.md](https://github.com/MeilleursAgents/react-mapbox-wrapper/blob/master/PULL_REQUEST_TEMPLATE.md) 😉 )

**Comment by kodermax** [comment]
eslint rule react/style-prop-object
We use a reserved attribute.

**Comment by danousna** [comment]
Closing this issue, the PR is merged and released in v2.0.0 https://github.com/MeilleursAgents/react-mapbox-wrapper/releases/latest
