### ISSUE TITLE
Add popupAnchor

### ISSUE THREAD

**Issue by kodermax** [MeilleursAgents/react-mapbox-wrapper#21]
**Is your feature request related to a problem? Please describe.**
It would be desirable to change the location of the popup relative to the marker

**Describe the solution you'd like**
Could you add anchor for the popup?

**Comment by ViBiOh** [comment]
Sorry for the long response time, we'll check that (in a way of spreading extra args to the Popup constructor)

**Comment by simrobin** [comment]
Hi @kodermax!

Thanks for the suggestion.

We added a way to provide `anchor` option to mapbox.Popup through the `popupAnchor` prop of the `Marker` component in [version 2.1.0](https://github.com/MeilleursAgents/react-mapbox-wrapper/releases/tag/v2.1.0).
