### ISSUE TITLE
I cant dynamically add markers to new locations.

### ISSUE THREAD

**Issue by ssspe** [MeilleursAgents/react-mapbox-wrapper#22]
**Describe the bug**
When adding new markers after a map has loaded, the markers do not change locations. However the pop ups do change their text.

**To Reproduce**
Load a map and render several markers using coordinates from props. Update the props and render the markers again. I would expect this to clear the old markers and render new ones in the new coordinates.

**Expected behavior**
I would expect this to clear the old markers and render new ones in the new coordinates.

**Screenshots**
![image](https://user-images.githubusercontent.com/40234672/51263193-ad5a7780-19ab-11e9-8c17-6fc07341d369.png)
![image](https://user-images.githubusercontent.com/40234672/51263263-cfec9080-19ab-11e9-8f94-cbf6b6599551.png)

As you can see, the marker is meant to have moved to the end of the next line but it has not updated as the props update. However the pop up text using the same prop object has updated?

**Device (please complete the following information):**
 - Browser [chrome]

If there is anymore information I can give please let me know! Love the work you guys are doing!

**Comment by ViBiOh** [comment]
Hi @ssspe !

Thank you for you interest and your report.

I've added an example of updating coordinates props of a Marker in https://github.com/MeilleursAgents/react-mapbox-wrapper/pull/23/files#diff-d8d2f1959d55acb9c951b82a74ff78eeR19 and it seems to work.

Can you check if it works for you, and if not, show us some code for reproducing it ?

**Comment by ssspe** [comment]
Hello @ViBiOh,

So I have found something strange which may just be my lack of understanding. If you pass coordinates to the marker as an array so:
`<Marker
              coordinates={ coordinates }
              map={this.map} />`
Where coordinates is in the form [-50, 0.1] the marker will not move.

However if you pass coordinates in the form {lat: -50, lng: 0.1} then it will update as shown in your example. I am happy to add my code if you need it?

**Comment by ViBiOh** [comment]
Yes, in fact for checking if [coordinates are equal](https://github.com/MeilleursAgents/react-mapbox-wrapper/blob/master/src/Helpers/index.js#L79) we only check the `object` form instead of the [LngLatLike](https://www.mapbox.com/mapbox-gl-js/api/#lnglatlike) pattern.

Doesn't seem complicated, we'll do that quickly.

**Comment by ViBiOh** [comment]
Fix in https://github.com/MeilleursAgents/react-mapbox-wrapper/releases/tag/v2.0.2
