### ISSUE TITLE
Full-Screen option works but I get an 'invalid prop' error

### ISSUE THREAD

**Issue by ChrisMuga** [MeilleursAgents/react-mapbox-wrapper#34]
if i set `withFullscreen = "true"` i get this error:

`Warning: Failed prop type: Invalid prop `withFullscreen` of type `string` supplied to `t`, expected `boolean``  

despite getting my fullscreen map.
![Screenshot from 2019-03-30 11-29-30](https://user-images.githubusercontent.com/20432690/55273694-ab802f00-52df-11e9-9d14-4bbfb9226469.png)

**Comment by ViBiOh** [comment]
Hi @ChrisMuga 

The correct way for setting a boolean in React is

```javascript
withFullscreen={true}
```

or simply juste the prop name, if it's boolean, it's assume to be `true`

```javascript
<MapboxMap withFullscreen />
```

If you set with `="true"` you indeed pass a string which is not the expected type.

**Comment by ChrisMuga** [comment]
Ah thank you, I have a clean console now...
