### ISSUE TITLE
Style prop value must be an object, despite map adopting custom style

### ISSUE THREAD

**Issue by ChrisMuga** [MeilleursAgents/react-mapbox-wrapper#35]
I get this error on my console:

`Style prop value must be an object`

if I add the prop

`style = {'mapbox://styles/mapbox/dark-v10'}`
or
`style = 'mapbox://styles/mapbox/dark-v10'`

the custom style, however,

 is still adopted, so it works as expected. 

![Screenshot from 2019-03-31 04-47-20](https://user-images.githubusercontent.com/20432690/55283629-18dba080-5370-11e9-96b7-fcaf76fac185.png)

**Comment by ViBiOh** [comment]
hi @ChrisMuga 

It seems that it's your `Map` component that raise this error, not our `MapboxMap` component.

Our composent accept a [`style`](https://github.com/MeilleursAgents/react-mapbox-wrapper#mapboxmap) prop as a string. It's used to specify the Mapbox style.

In React, `style` prop is used to pass inline-style to HTML component, and should be passed as an object, [as described in the official doc](https://reactjs.org/docs/dom-elements.html#style).

So, the appropriate way to use is

```javascript
<MapboxMap style="mapbox://styles/mapbox/dark-v10" />
```

**Comment by ViBiOh** [comment]
Documentation is now up-to-date, thank you for spotting it ;)
