### ISSUE TITLE
modules not found

### ISSUE THREAD

**Issue by VictorBaudot** [MeilleursAgents/react-mapbox-wrapper#40]
I just started an app to try your tool but I don't understand why I have to manually add dependencies like `@turf/cricle` or `mapbox-gl`

![image](https://user-images.githubusercontent.com/33088396/58703225-9b083580-83b0-11e9-8381-97a43fc8bf5c.png)

**Comment by ViBiOh** [comment]
Hi @VictorBaudot,

All this dependencies, and more, are [`peerDependencies`](https://nodejs.org/en/blog/npm/peer-dependencies/) of npm. The main reason is if we bundle mapbox, turf and co in our library, when you want a newer version, you're dependant on us.

With peer dependencies, as long your version match our requirements, you can choose the version your want. It also help to keep bundle size low. If your use multiple libraries relying on mapbox, you have only one version with `peerDepencies`, or many if all library bundle its version.

**Comment by VictorBaudot** [comment]
OK interesting, never used `peerDeps` before
