### ISSUE TITLE
Module @turf/circle missing from package

### ISSUE THREAD

**Issue by naomigrace** [MeilleursAgents/react-mapbox-wrapper#69]
**Describe the bug**
@turf/circle is not included in react-mapbox-wrapper even though it's used within the package.
`Module not found: Error: Can't resolve '@turf/circle' in '/myrepo/node_modules/react-mapbox-wrapper/build'`

**To Reproduce**
1. `npm i react-mapbox-wrapper` in an empty CRA
2. See the error above

**Comment by ViBiOh** [comment]
All this dependencies, and more, are peerDependencies of npm. The main reason is if we bundle mapbox, turf and co in our library, when you want a newer version, you're dependant on us.

With peer dependencies, as long your version match our requirements, you can choose the version your want. It also help to keep bundle size low. If your use multiple libraries relying on mapbox, you have only one version with peerDepencies, or many if all library bundle its version
